### ISSUE TITLE
Question: How to install/setup

### ISSUE THREAD

**Issue by poudenes** [pteich/esphomekit#1]
Hi There,

I was happy to see an option to make ESPhome visible in homekit. But can you tell me how to install this?
I habe ESPhome on Home Assistant and have 9 wall switches wired.

Cheers,
Peter

**Comment by ihrapsa** [comment]
If you have HomeAssistant already setup I really recommend using the native [HomeKit](https://www.home-assistant.io/integrations/homekit/) integration.

**Comment by poudenes** [comment]
Hi,

Already have that. But Want to see if I can create a backup workaround when HA will be offline, crash etc. 
If ESPhome is directly in Homekit. I can create some backup automations in there. Check if sensor is unavailable (home assistant) if so then run the automation to turn on a light.

**Comment by ihrapsa** [comment]
I see, a backup is always a good idea. However, you still need to have this bridge up and running to have the esphome devices exposed to HomeKit. 

I think the best approach would be to either have homekit native into esphome (but that’s unlikely to happen) or wait for matter support.
This way you won’t need any bridge.
